### ISSUE TITLE
Layer view breaks (Possible python mixup?)

### ISSUE THREAD

**Issue by moovida** [g3w-suite/g3w-admin#303]
Hi I just finished the environment setup on ubuntu 21.10 with python 3.9. 

I am running this from visual studio (even if I do not think that has something to do with it) and it signals me that I am running with the proper virtual env g3wsuite I created before.

Everything worked in the sense that I was able to startup, create a project and upload a QGIS project. To make sure the data would be ok, I placed them into the project_data folder and loaded them from there into QGIS. Then saved and loaded that project into the suite.

If I click on the layer view of the project, I am getting the following error. Consider that in the map view the layers are not visible (it tells they could not be loaded). 

The error:
```
Request Method: | GET
-- | --
http://127.0.0.1:8000/en/qdjango/natural_earth/projects/g3wtestqgs/layers/
2.2.24
KeyError
'caching_layer_action'
/home/hydrologis/development/G3WSUITE/g3w-admin/g3w-admin/core/templatetags/g3wadmin_tags.py in g3wadmin_layer_actions, line 94
/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/bin/python3.9.7
['/home/hydrologis/development/G3WSUITE/g3w-admin/g3w-admin',  
'/home/hydrologis/.vscode/extensions/ms-python.python-2021.10.1365161279/pythonFiles/lib/python/debugpy/_vendored/pydevd',  
'/usr/lib/python39.zip',  
'/usr/lib/python3.9',  
'/usr/lib/python3.9/lib-dynload', 
 '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages',  
'/usr/local/lib/python3.9/dist-packages',  
'/usr/lib/python3/dist-packages',  
'/home/hydrologis/development/G3WSUITE/g3w-admin',  '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/odf',  '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/odf',  '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/odf',  '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/odf',  '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/odf',  '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/odf',  '/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/odf',  '/home/hydrologis/development/G3WSUITE/g3w-admin/g3w-admin']
Fri, 22 Oct 2021 12:27:37 +0000
```
The strange thing I notice in my limited knowledge is that the system python is also referenced. 

The resulting error in the terminal, maybe more verbose:
```
Traceback (most recent call last):
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hydrologis/development/G3WSUITE/virtualenvs/g3wsuite/lib/python3.9/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/hydrologis/development/G3WSUITE/g3w-admin/g3w-admin/core/templatetags/g3wadmin_tags.py", line 94, in g3wadmin_layer_actions
    no1.append(no[oaction])
KeyError: 'caching_layer_action'
```

Any idea what could be going on?

**Comment by wlorenzetti** [comment]
@moovida I fixed it, this issue happend because you don't active 'caching' module in your local_settings.py adding it to G3WADMIN_LOCAL_MORE_APPS.

**Comment by moovida** [comment]
Thanks @wlorenzetti, I just wanted to test it, but it is still failing. Is it enough for me to make a git pull origin dev, right? And then restart the server?

**Comment by moovida** [comment]
Hold on, I think it is a bit below:

```
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/hydrologis/development/G3WSUITE/g3w-admin/g3w-admin/core/templatetags/g3wadmin_tags.py", line 96, in g3wadmin_layer_actions
    no1.append(no[oaction])
KeyError: 'qplottly_layer_action'
```

**Comment by wlorenzetti** [comment]
ok sorry I reply to fast I have to fix for every not defautl moduels.

**Comment by moovida** [comment]
Ok, this works now, thanks.
